apiVersion: v1
kind: Service
metadata:
  name: mustacheme
  labels:
    app: mustacheme
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: mustacheme
  selector:
    app: mustacheme